### ISSUE TITLE
problems about annotations 

### ISSUE THREAD

**Issue by ygwangthu** [arielai/youtube_3d_hands#12]
1. In json file, there are two keys: "images" and "annotations". I found that 'image_id' in "annotations" are not consistent with "images". That is, no all 'image_id' in "images" are used. The json file can be concisely processed 

2. another problem is that not all hands in the given frames have annotations. Most of them give 1 hand only. Is it available to label full hands for all the frames?

**Comment by dkulon** [comment]
Hi @ygwangthu,

1. Thank you for your observation.

2. I have selected to annotate as many hands for each image as possible. The reason why there is mostly one annotation per image is because the remaining annotations did not meet automated filtering criteria based on the fitting error.

Best,
Dominik
